const LEGAL_EFFECTIVE_DATE = "14 July 2026"
const LEGAL_LAST_UPDATED = "14 July 2026"
const LEGAL_CONTACT_EMAIL = "hmcoding.h@gmail.com"
const LEGAL_GRIEVANCE_EMAIL = "support@convertly.app"
const LEGAL_ENTITY_NAME = "HM Coding"

export {
  LEGAL_CONTACT_EMAIL,
  LEGAL_EFFECTIVE_DATE,
  LEGAL_ENTITY_NAME,
  LEGAL_GRIEVANCE_EMAIL,
  LEGAL_LAST_UPDATED,
}
