const LEGAL_EFFECTIVE_DATE = "8 July 2026"
const LEGAL_LAST_UPDATED = "8 July 2026"
const LEGAL_CONTACT_EMAIL = "support@convertly.app"

export { LEGAL_CONTACT_EMAIL, LEGAL_EFFECTIVE_DATE, LEGAL_LAST_UPDATED }
